# Uncomment this file to enable multilanguage site support

#[fr]
#languageName = "Français"
#languagedirection = "ltr"
#title = "Example Site"
#weight = 1

#[en]
#languageName = "English"
#languagedirection = "ltr"
#title = "Example Site"
#weight = 2